# development, test
version: '3'
services:
    app:
        build:
            context: .
            dockerfile: containers/rails/Dockerfile
        env_file: .env
        environment:
            TZ: "Asia/Tokyo"
        command: bundle exec rails s -p 3000 -b 0.0.0.0
        volumes:
            - .:/cookpad-internship-2020-summer-pbl
            - public-data:/cookpad-internship-2020-summer-pbl/public
            - tmp-data:/cookpad-internship-2020-summer-pbl/tmp
            - log-data:/cookpad-internship-2020-summer-pbl/log
        ports:
            - "3000:3000"
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: containers/mysql/Dockerfile
        entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
        env_file: 
            - .env
        environment:
            TZ: "Asia/Tokyo"
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    public-data:
    tmp-data:
    log-data:
    db-data: